import type { CorporateRouteRequest } from "./types";

export const corporateRouteRequestsMockData: CorporateRouteRequest[] = [
  {
    id: 701,
    clientName: "TechCorp Inc.",
    routeName: "Avrupa Yakası Sabah Servisi",
    startPoint: "Yenibosna Metrobüs",
    endPoint: "TechCorp Maslak Kampüsü",
    direction: "Gidiş",
    shift: "Sabah",
    workingDays: "Pzt - Cum",
    plannedStartTime: "07:10",
    stopCount: 8,
    employeeCount: 46,
    estimatedDistanceKm: 31,
    estimatedDurationMin: 62,
    status: "submitted",
  },
  {
    id: 702,
    clientName: "TechCorp Inc.",
    routeName: "Anadolu Yakası Sabah Servisi",
    startPoint: "Kozyatağı Metro",
    endPoint: "TechCorp Maslak Kampüsü",
    direction: "Gidiş",
    shift: "Sabah",
    workingDays: "Pzt - Cum",
    plannedStartTime: "07:00",
    stopCount: 9,
    employeeCount: 58,
    estimatedDistanceKm: 38,
    estimatedDurationMin: 74,
    status: "requested",
  },
  {
    id: 703,
    clientName: "Anka Finans",
    routeName: "Ataşehir Akşam Dönüş",
    startPoint: "Anka Finans Genel Müdürlük",
    endPoint: "Ümraniye - Çekmeköy Hattı",
    direction: "Dönüş",
    shift: "Akşam",
    workingDays: "Pzt - Cum",
    plannedStartTime: "18:15",
    stopCount: 6,
    employeeCount: 34,
    estimatedDistanceKm: 24,
    estimatedDurationMin: 48,
    status: "revision_requested",
  },
  {
    id: 704,
    clientName: "Nova Üretim A.Ş.",
    routeName: "Kemalpaşa Fabrika Gidiş",
    startPoint: "Bornova Metro",
    endPoint: "Nova Üretim Fabrika",
    direction: "Gidiş",
    shift: "Vardiya 1",
    workingDays: "Pzt - Cmt",
    plannedStartTime: "06:20",
    stopCount: 11,
    employeeCount: 72,
    estimatedDistanceKm: 29,
    estimatedDurationMin: 55,
    status: "approved",
  },
];
