import type { CorporateEmployee } from "./types";

export const corporateEmployeesMockData: CorporateEmployee[] = [
  {
    employeeId: 1001,
    firstName: "Ayşe",
    lastName: "Demir",
    department: "Finans",
    email: "ayse.demir@techcorp.com",
    phone: "+90 532 555 10 11",
    district: "Kadıköy",
    preferredStop: "Kozyatağı Metro",
    isActive: true,
  },
  {
    employeeId: 1002,
    firstName: "Burak",
    lastName: "Çelik",
    department: "Operasyon",
    email: "burak.celik@techcorp.com",
    phone: "+90 533 555 20 22",
    district: "Ümraniye",
    preferredStop: "Çakmak Köprüsü",
    isActive: true,
  },
  {
    employeeId: 1003,
    firstName: "Selin",
    lastName: "Aksoy",
    department: "İnsan Kaynakları",
    email: "selin.aksoy@techcorp.com",
    phone: "+90 534 555 30 33",
    district: "Bahçelievler",
    preferredStop: "Yenibosna Metrobüs",
    isActive: false,
  },
  {
    employeeId: 1004,
    firstName: "Emre",
    lastName: "Yıldız",
    department: "Yazılım",
    email: "emre.yildiz@techcorp.com",
    phone: "+90 535 555 40 44",
    district: "Sarıyer",
    preferredStop: "Hacıosman Metro",
    isActive: true,
  },
];
